server:
  port: 9000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${AURORA_BLOG_DATABASE_HOST:localhost}:${AURORA_BLOG_DATABASE_PORT:3306}/blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true&createDatabaseIfNotExist=true
    username: ${AURORA_BLOG_DATABASE_USERNAME:root}
    password: ${AURORA_BLOG_DATABASE_PASSWORD:password}
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: ${AURORA_BLOG_REDIS_HOST:localhost}
    port: ${AURORA_BLOG_REDIS_PORT:6379}
    password: ${AURORA_BLOG_REDIS_PASSWORD:password}
    database: 0
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 100
        max-wait: 10000

  rabbitmq:
    host: ${AURORA_BLOG_RABBITMQ_HOST:localhost}
    port: ${AURORA_BLOG_RABBITMQ_PORT:5672}
    username: ${AURORA_BLOG_RABBITMQ_USERNAME:username}
    password: ${AURORA_BLOG_RABBITMQ_PASSWORD:password}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

  elasticsearch:
    rest:
      uris: ${AURORA_BLOG_ELASTICSEARCH_URL:localhost}

  mail:
    host: smtp.163.com
    username: ${AURORA_BLOG_MAIL_USERNAME:username}
    password: ${AURORA_BLOG_MAIL_PASSWORD:password}
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  secret: aurora

search:
  mode: elasticsearch

upload:
  mode: oss
  oss:
    url: ${AURORA_BLOG_OSS_URL}
    endpoint: ${AURORA_BLOG_OSS_ENDPOINT:oss-cn-beijing.aliyuncs.com}
    accessKeyId: ${AURORA_BLOG_OSS_ACCESS_KEY_ID}
    accessKeySecret: ${AURORA_BLOG_OSS_ACCESS_KEY_SECRET}
    bucketName: ${AURORA_BLOG_OSS_BUCKET_NAME}
  minio:
    url: http://minio的ip:9000/
    endpoint: http://minio的ip:9000
    accesskey: 用户名
    secretKey: 密码
    bucketName: 桶的名称

website:
  url: ${AURORA_BLOG_WEBSITE_URL:https://www.devillusion.asia}

qq:
  app-id: QQ APPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}
